### PR TITLE
[langdale] clang: fix reproducible build

### PR DESCRIPTION
**Pull request by cheeyanglee**
backport 2 patch from master to fix reproducible build.

---
### Contributor checklist

- [x] Changes have been tested
- [x] `Signed-off-by` is present
- [x] The PR complies with the [Open Embedded Commit Patch Message Guidelines](http://www.openembedded.org/wiki/Commit_Patch_Message_Guidelines)

### Reviewer Guidelines
- When submitting a review, please pick:
  - '*Approve*' if this change would be acceptable in the codebase (even if there are minor or cosmetic tweaks that could be improved).
  - '*Request Changes*' if this change would not be acceptable in our codebase (e.g. bugs, changes that will make development harder in future, security/performance issues, etc).
  - '*Comment*' if you don't feel you have enough information to decide either way (e.g. if you have major questions, or you don't understand the context of the change sufficiently to fully review yourself, but want to make a comment)

### CODE REVIEW

**Comment by shr-project** [comment]
Is the python3targetconfig needed in langdale as well? With this change clang fails to build for me in langdale builds with:

```
work-shared/llvm-project-source-15.0.6-r0/git/lldb/CMakeLists.txt:60 (message):
|   Crosscompiling LLDB with Python requires manually setting
|   LLDB_PYTHON_RELATIVE_PATH.
```

If I revert the python3targetconfig change, then target clang builds fine again in langdale builds.

**Comment by kraj** [comment]
> Is the python3targetconfig needed in langdale as well? With this change clang fails to build for me in langdale builds with:
> 
> ```
> work-shared/llvm-project-source-15.0.6-r0/git/lldb/CMakeLists.txt:60 (message):
> |   Crosscompiling LLDB with Python requires manually setting
> |   LLDB_PYTHON_RELATIVE_PATH.
> ```
> 
> If I revert the python3targetconfig change, then target clang builds fine again in langdale builds.

hmmm I thought it was needed on langdale too. but its ok if it is not needed. Do due dilligence, we can revert it.

**Comment by shr-project** [comment]
@cheeyanglee Can you please reply as well? I can PR the revert, but wanted confirmation from you before doing that as I assume you've built clang with your PR in langdale before it as submitted.

**Comment by cheeyanglee** [comment]
I missed the previous notification. I think python3targetconfig is optional, picking the patch just because it include fix for 
`WARNING: clang-15.0.6-r0 do_package_qa: QA Issue: File /usr/lib/liblldb.so.15.0.6 in package liblldb contains reference to TMPDIR [buildpaths]`

**Pull request merged**
