### PR TITLE
busybox: remove clang fixes, issues resolved in 1.35

### PR DESCRIPTION
**Pull request by rossburton**

### CODE REVIEW

**Comment by zandrey** [comment]
@rossburton 

I was looking at exactly this issue, and it looks like _busybox_ commit `1f925038a ("*: generalize "const trick"")` moved this to `CONFIG_EXTRA_CFLAGS`.

In order to apply this clean, it should be complemented with setting `-DBB_GLOBAL_CONST=''` in `CONFIG_EXTRA_CFLAGS` and it should be done in either here in append or in _OE-Core_.

I was not able to come up with the solution for now, do you maybe have a complementing commit in _OE-Core_ for this?

-- andrey

**Comment by rossburton** [comment]
Improved blind commit pushed.  It's quicker to let the CI run here than build a local clang... :)

**Comment by zandrey** [comment]
@rossburton 
Awesome! The fix was actually easier than I expected!

Thanks a lot!

-- andrey

**Comment by rossburton** [comment]
It hasn't passed the CI yet! 🤞

**Comment by rossburton** [comment]
That is failing due to opkg update timing out, Khem: is that a known CI problem?

**Comment by kraj** [comment]
> That is failing due to opkg update timing out, Khem: is that a known CI problem?

Yes it sometimes fails with this error no idea why

**Comment by kraj** [comment]
this fix is not sufficient, we still need to patch busybox a bit. I have completed this fix with https://github.com/kraj/meta-clang/pull/554 so I am closing this one, please take any further discussions to new pull

**Comment by rossburton** [comment]
Thanks khem!

**Pull request closed without merging**
