### PR TITLE
clang: Merge llvm-common into clang

### PR DESCRIPTION
**Pull request by zboszor**
Signed-off-by: Zoltán Böszörményi <zboszor@pr.hu>

---
### Contributor checklist

- [x] Changes have been tested
- [x] `Signed-off-by` is present
- [x] The PR complies with the [Open Embedded Commit Patch Message Guidelines](http://www.openembedded.org/wiki/Commit_Patch_Message_Guidelines)

### Reviewer Guidelines
- When submitting a review, please pick:
  - '*Approve*' if this change would be acceptable in the codebase (even if there are minor or cosmetic tweaks that could be improved).
  - '*Request Changes*' if this change would not be acceptable in our codebase (e.g. bugs, changes that will make development harder in future, security/performance issues, etc).
  - '*Comment*' if you don't feel you have enough information to decide either way (e.g. if you have major questions, or you don't understand the context of the change sufficiently to fully review yourself, but want to make a comment)

### CODE REVIEW

**Comment by zboszor** [comment]
@kraj Now libclc builds with LLVM 11 properly, started build testing it with your LLVM 12 branch rebased over these changes.

**Comment by zboszor** [comment]
@kraj The built test against LLVM 12 also succeeded with x86-64 target now, also for libclc-native. Running the build test for 32-bit x86 target now.

**Comment by zboszor** [comment]
@kraj The build test against LLVM 12 just finished successfully for 32-bit x86 target.
I had to omit `meta-intel` because it's not currently compatible with LLVM 12.

**Comment by zboszor** [comment]
@kraj This CI failure seems to have nothing to do with my changes.

**Review by kraj — APPROVED** [review]
lgtm

**Pull request merged**
