### PR TITLE
clang: make libedit optional

### PR DESCRIPTION
**Pull request by jyong2**
Allows libedit to dependency to be disabled via
PACKAGECONFIG_remove.

Signed-off-by: Yong, Jonathan <jonathan.yong@intel.com>

### CODE REVIEW

**Comment by jyong2** [comment]
Very odd, how is one supposed to make libedit optional if it is still required when disabled? Seems to be passing locally.

**Comment by kraj** [comment]
This is building nativesdk-clang have you tried building that locally

**Comment by jyong2** [comment]
I don't see -DLLVM_ENABLE_LIBEDIT being used anywhere in the logs.
Local nativesdk-clang is passing.

**Comment by jyong2** [comment]
I can't seem to pass the LLVM/LLDB arguments down to the "Configuring NATIVE LLVM" part after doing cleansstate. Any pointers on how to continue?

**Comment by kraj** [comment]
> I can't seem to pass the LLVM/LLDB arguments down to the "Configuring NATIVE LLVM" part after doing cleansstate. Any pointers on how to continue?

lldb has another knob to control it `LLDB_DISABLE_LIBEDIT`. you need to set that along as well

**Comment by jyong2** [comment]
I am currently using:
PACKAGECONFIG[libedit] = "-DLLVM_ENABLE_LIBEDIT=ON -DLLDB_DISABLE_LIBEDIT=0,-DLLVM_ENABLE_LIBEDIT=OFF -DLLDB_DISABLE_LIBEDIT=1,libedit libedit-native"

So LLDB is already set.

It's not passed to the [532/4647] Configuring NATIVE LLVM... stage.

**Comment by kraj** [comment]
Interesting should it be ON/OFF

**Comment by jyong2** [comment]
OK, will try that, I saw 0/1 used when grepping through for LIBEDIT.

**Comment by jyong2** [comment]
Looks like it is still actually broken when reaching "Configuring NATIVE LLVM" if libedit is disabled. Any idea how the cmake command for that stage is generated?

It looks like:
cd ..../work/corei7-64-ese-linux/clang/9.0.0-r0/build/NATIVE &&...../recipe-sysroot-native/usr/bin/cmake

**Comment by kraj** [comment]
merged with changes to fix the build issues via https://github.com/kraj/meta-clang/pull/217

**Pull request closed without merging**
