### PR TITLE
kirkstone: backport clang from scarthgap

### PR DESCRIPTION
**Pull request by adalessandro**
Links:
https://github.com/kraj/meta-clang/issues/1023
https://github.com/OSSystems/meta-browser/issues/842

---
### Contributor checklist

- [ ] Changes have been tested
- [x] `Signed-off-by` is present
- [ ] The PR complies with the [Open Embedded Commit Patch Message Guidelines](http://www.openembedded.org/wiki/Commit_Patch_Message_Guidelines)

### Reviewer Guidelines
- When submitting a review, please pick:
  - '*Approve*' if this change would be acceptable in the codebase (even if there are minor or cosmetic tweaks that could be improved).
  - '*Request Changes*' if this change would not be acceptable in our codebase (e.g. bugs, changes that will make development harder in future, security/performance issues, etc).
  - '*Comment*' if you don't feel you have enough information to decide either way (e.g. if you have major questions, or you don't understand the context of the change sufficiently to fully review yourself, but want to make a comment)

### CODE REVIEW

**Comment by adalessandro** [comment]
@kraj @MaxIhlenfeldt I've created this (still) work in progress PR so we can discuss on top of it:

* This PR only backports `clang` from scarthgap. No other recipes nor changes are backported.
* Chromium `129.0.6668.100` from `meta-browser` [0] successfully builds (with a few rust backport fixes).

[0] https://github.com/OSSystems/meta-browser/commit/f988d616d37ddf160d3d747ed54d0a66d549f499

**Comment by adalessandro** [comment]
>     * Is it okay to just backport the specific `clang` recipes part?
Regarding the above, definitely other parts in this layer (that depends on clang) need to be updated as well.

**Comment by MaxIhlenfeldt** [comment]
Will defer to kraj as I'm not too familiar with meta-clang.

**Comment by petermarko** [comment]
This will not be accepted, LTS branches do not accept major version updates.
I wonder if this could be submitted to https://git.yoctoproject.org/meta-lts-mixins/ as new branch kirkstone/clang

**Comment by adalessandro** [comment]
> This will not be accepted, LTS branches do not accept major version updates. I wonder if this could be submitted to https://git.yoctoproject.org/meta-lts-mixins/ as new branch kirkstone/clang

@petermarko thanks, you're right, so I'll close this one. Just in case, do you know who should I ask in that case? AFAICS Scott <scott.murray@konsulko.com> is the maintainer, but I couldn't reach him yet.

**Comment by petermarko** [comment]
Afaik each branch of mixin layers repo is maintained by someone else.
So you need to find someone willing to be the maintainer of kirkstone/clang branch or become the maintainer yourself.

**Pull request closed without merging**
