### PR TITLE
Revert "python3: Use gcc for riscv/aarch64 and all musl"

### PR DESCRIPTION
**Pull request by otavio**
This reverts commit 3882c27310b16e6fc097cca1966cea591769cc5c.

---
### Contributor checklist

- [x] Changes have been tested
- [x] `Signed-off-by` is present
- [ ] The PR complies with the [Open Embedded Commit Patch Message Guidelines](http://www.openembedded.org/wiki/Commit_Patch_Message_Guidelines)

### CODE REVIEW

**Review by kraj — COMMENTED** [review]
@otavio I think 
```
TOOLCHAIN:pn-python3:aarch64 = "gcc"
```
can be removed since https://lists.openembedded.org/g/openembedded-core/message/164192 is now in core. But I am not sure about other changes e.g. rv/musl still. Have you tested these all ?

**Comment by otavio** [comment]
I just tried this and musl still fails. I reworked the commit.

**Review by kraj — APPROVED** [review]
lgtm

**Comment by otavio** [comment]
@kraj please backport to kirkstone as well if it works fine.

**Comment by otavio** [comment]
The error doesn't seem related to this PR.

**Comment by kraj** [comment]
> The error doesn't seem related to this PR.

yes, I have rerun the CI just to avoid that issue.

**Pull request merged**
