### PR TITLE
clang: Build float128 soft float builtins for x86_64

### PR DESCRIPTION
**Pull request by quaresmajose**
Signed-off-by: Jose Quaresma <jose.quaresma@foundries.io>

---
### Contributor checklist

- [x] Changes have been tested
- [x] `Signed-off-by` is present
- [x] The PR complies with the [Open Embedded Commit Patch Message Guidelines](http://www.openembedded.org/wiki/Commit_Patch_Message_Guidelines)

### Reviewer Guidelines
- When submitting a review, please pick:
  - '*Approve*' if this change would be acceptable in the codebase (even if there are minor or cosmetic tweaks that could be improved).
  - '*Request Changes*' if this change would not be acceptable in our codebase (e.g. bugs, changes that will make development harder in future, security/performance issues, etc).
  - '*Comment*' if you don't feel you have enough information to decide either way (e.g. if you have major questions, or you don't understand the context of the change sufficiently to fully review yourself, but want to make a comment)

### CODE REVIEW

**Comment by quaresmajose** [comment]
One side effect of this patch is that it breaks the **mpfr** build with clang https://github.com/foundriesio/meta-lmp/commit/8154f36a67c9c9357d0ebc093c31f6efd362b0b6

**Comment by kraj** [comment]
@quaresmajose thanks for the patch, I see that https://reviews.llvm.org/D53608 still has some changes planned, so its not yet final, so we should wait for taking this patch into release. It might need to address the feedback and go through some more review cycles.

**Comment by quaresmajose** [comment]
Thanks for the review, I will keep an eye on it and maybe can try to address the feedback.

**Comment by quaresmajose** [comment]
there is no nativity upstream on https://reviews.llvm.org/D53608 and so close this.

**Pull request closed without merging**
