### PR TITLE
Convert to new override syntax

### PR DESCRIPTION
**Pull request by shr-project**

### CODE REVIEW

**Comment by kraj** [comment]
I have merged a version bump. Can you rebase and upload again please ?

**Comment by priv-kweihmann** [comment]
Any news on this one?

**Comment by kraj** [comment]
Can you check latest master ?

**Comment by kraj** [comment]
https://github.com/kraj/meta-clang/pull/488

**Comment by kraj** [comment]
closing as it seems to be fixed. if not please open new PR

**Pull request closed without merging**
