### PR TITLE
Add a recipe for lldb

### LINKED ISSUE #27: Add lldb?
Hi!

I have a project that needs lldb in the toolchain in addition to clang.
Would you consider adding that?

### PR DESCRIPTION
**Pull request by Tragetaschen**
Fixes #27 

I had started that recipe for the meta-aspnet layer using the morty branch (https://github.com/Tragetaschen/meta-aspnet/blob/master/recipes-dotnet/lldb/lldb_git.bb) and took the time to adapt it to the master branch.

<s>The git commit for lldb is from roughly the time the other clang commits are (beginning of December). Most recent, versions started using llvm-config's new --cmakedir argument and so would need to be updated in tandem.</s>
The git commit is the current one from lldb's `release_40` branch.

I have tested the build in an otherwise morty-based environment for my ARM target (by deactivating the `systemd-boot_%.bbappend`)

### CODE REVIEW

**Comment by Tragetaschen** [comment]
My git branching "skills" failed me...

**Comment by Tragetaschen** [comment]
That (actually correct) build succeeded as well

**Comment by kraj** [comment]
applied with db97660178a4fdb566ab4ddba0e5edd0efc85820

**Comment by Tragetaschen** [comment]
Thanks!

**Pull request closed without merging**
