### PR TITLE
[new branch: kirkstone-clang18]: Backport from scarthgap

### PR DESCRIPTION
**Pull request by adalessandro**
This is a proposal for a new branch `kirkstone-clang18`, as discussed in the
 `yocto-patches` mailing list. See https://lists.yoctoproject.org/g/yocto-patches/message/783

The following branch request is based on scarthgap with the required compatibility
changes on top for the sake of simplicity.

**NOTE:** this is a new branch request, not to be merged to `scarthgap` branch.

Related to:
* https://github.com/kraj/meta-clang/pull/1024
* https://github.com/OSSystems/meta-browser/pull/843

### CODE REVIEW

**Comment by adalessandro** [comment]
FYI @kraj @MaxIhlenfeldt @petermarko

**Comment by kraj** [comment]
I guess you are asking to create `kirkstone-clang18` branch rooted from `scarthgap` branch ?

**Comment by adalessandro** [comment]
> I guess you are asking to create `kirkstone-clang18` branch rooted from `scarthgap` branch ?

Yes, indeed. Feedback welcome :-)

**Comment by adalessandro** [comment]
@kraj let me know if that's fine or this PR needs to be amended. Thanks in advance.

**Comment by kraj** [comment]
> @kraj let me know if that's fine or this PR needs to be amended. Thanks in advance.

yes. I have created a new branch named `kirkstone-clang18` this PR perhaps is better to be rebased on it.

**Comment by adalessandro** [comment]
> > @kraj let me know if that's fine or this PR needs to be amended. Thanks in advance.
> 
> yes. I have created a new branch named `kirkstone-clang18` this PR perhaps is better to be rebased on it.

Great. Rebased!

**Review by kraj — APPROVED** [review]
lgtm

**Pull request merged**
