### PR TITLE
do not use compiler arguments for clang-tidy (backport to dunfell)

### PR DESCRIPTION
**Pull request by danieldittmann**
clang-tidy does not know compiler arguments

Signed-off-by: Daniel Dittmann <daniel.dittmann@rohde-schwarz.com>

### CODE REVIEW

**Comment by danieldittmann** [comment]
It overlaps with #396, but I need the fix also in dunfell branch.

**Comment by kraj** [comment]
thanks @danieldittmann  we should do a merge into master which should happen soon and then do a backport into dunfell. Can you backport the exact patch ? keeps the history logical that way

**Review by kraj — CHANGES_REQUESTED** [review]
please do a backport from master perhaps with `git cherry-pick -s`

**Comment by danieldittmann** [comment]
> 
> 
> please do a backport from master perhaps with `git cherry-pick -s`

Ok, I'll do it soon as #396 is on master.

**Comment by kraj** [comment]
thanks master pull is merged now. Please update

**Comment by danieldittmann** [comment]
> thanks master pull is merged now. Please update
@kraj: backport done. I hope it's fine.

**Review by kraj — APPROVED** [review]

**Pull request merged**
