### PR TITLE
Add adb daemon

### PR DESCRIPTION
**Pull request by Ecordonnier**
---
### Contributor checklist

- [X] Changes have been tested
- [X] `Signed-off-by` is present
- [X] The PR complies with the [Open Embedded Commit Patch Message Guidelines](http://www.openembedded.org/wiki/Commit_Patch_Message_Guidelines)

### Reviewer Guidelines
- When submitting a review, please pick:
  - '*Approve*' if this change would be acceptable in the codebase (even if there are minor or cosmetic tweaks that could be improved).
  - '*Request Changes*' if this change would not be acceptable in our codebase (e.g. bugs, changes that will make development harder in future, security/performance issues, etc).
  - '*Comment*' if you don't feel you have enough information to decide either way (e.g. if you have major questions, or you don't understand the context of the change sufficiently to fully review yourself, but want to make a comment)

### CODE REVIEW

**Review by kraj — COMMENTED** [review]
whats the plan to upstream these patches to android

**Comment by Ecordonnier** [comment]
Do you mean upstream to Debian? On Android the patches for adbd don't make sense. The makefiles don't exist on Android (they were introduced by Debian). I will try to upstream the makefiles patches to Debian.

**Comment by kraj** [comment]
> Do you mean upstream to Debian? On Android the patches for adbd don't make sense. The makefiles don't exist on Android (they were introduced by Debian). I will try to upstream the makefiles patches to Debian.

debian, so we can share some of the maintenance

**Comment by Ecordonnier** [comment]
I'll try to upstream what is upstreamable to Debian.

**Comment by Ecordonnier** [comment]
@kraj thank you for merging this PR. I'm not sure what the best channel to discuss moving this recipe to meta-openembedded. Should I open an issue in github? Or maybe the meta-openembedded mailing list?

It is quite easily possible to compile this recipe without clang (just requires one straightforward patch), so this could be moved to meta-openembedded and make it usable without the clang dependency which is quite big in terms of compilation time. However it's not clear to me why the version from meta-openembedded compiles its own libselinux instead of depending on the generic libselinux. Is it done that way so that it doesn't need to be in meta-oe/dynamic-layers/selinux?

Also, this recipe, while newer than the version in meta-openembedded, may break some functionality provided by the patches in meta-openembedded, so there is a risk of regression.

Do you agree it makes sense to move it to meta-openembedded/meta-oe/dynamic-layers/selinux ?

**Pull request merged**
